### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Wiffi**
Commit

### CODE REVIEW

**Comment by amazinigmech2418** [comment]
If you're actually a bot, no. We don't need a bot destroying waffle.

**Comment by Wiffi** [comment]
i am not desystoring,

**Comment by amazinigmech2418** [comment]
Not now. Also, how do I know you are just a bot? I don't think bots can code and comment with incorrect grammar or any grammar.

**Comment by redmangospros** [comment]
THE BOT IS SAFE! IT IS BY ME! 

<small>  IT IS A HIGH TECH BOT<small>

**Comment by amazinigmech2418** [comment]
Can I see the code then? I won't trust a bot that I can't see the code of.

**Comment by redmangospros** [comment]
i will give some
` if respone (get) make comment`

**Comment by redmangospros** [comment]
OKAY, it's not a bot! it's me, I just to make it like a bot

**Comment by amazinigmech2418** [comment]
OK. Why did you want to make a fake bot?

**Comment by redmangospros** [comment]
It's not fake, i just programed it it has push acces

**Comment by amazinigmech2418** [comment]
Then can I see the code?

**Comment by redmangospros** [comment]
okay, it;s fake.

**Pull request merged**
