### PR TITLE
Remove Canvas

### PR DESCRIPTION
**Pull request by radioblahaj**
As Stated in #12

### CODE REVIEW

**Review by AmazingMech2418 — COMMENTED** [review]
THERE IS NO WAY WE'RE DOING THIS!

**Comment by radioblahaj** [comment]
Make it show in an new page, when you click create

**Comment by AmazingMech2418** [comment]
THERE IS NO WAY WE ARE DOING THIS! I WON'T STOP CLOSING THIS REQUEST!

**Comment by kerrtravers** [comment]
@redmangospros Please keep in mind that @amazinigmech2418 is the one who actually owns this.

**Comment by AmazingMech2418** [comment]
@vutondesign You're correct. @redmangospros may have made the organization, but I made the initial repository.

**Pull request closed without merging**
